### ISSUE TITLE
Add unset & default conf items for uses cases to the appropriate use case conf file

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplus#129]
METplus will only place conf items and their values in the metplus_final.conf that are explicitly set in a conf file. For certain conf items, the wrappers assume a default value and so it isn't required to explicitly set them. To make metplus_final.conf the most useful for the use cases included with METplus, it would be helpful to set every conf item used by the use cases in the use case conf file. That way, a user can see all the available config options for that use case in metplus_final.conf.

**Comment by georgemccabe** [comment]
I thought of a solution that would help with this issue. We could wrap each getter method from produtil with a met_util function of the same name and same arguments (with the addition of the conf object) to be used when a default value is specified. This function would check if the conf item is set using has_option. If it is not set, print a warning saying METplus is using the default value, set the value in the conf object, and return the default value.

This would help with Dan's issue in a few ways. You could clearly see in the log which default values are being used, so you can set these values in the conf files if you desire. It would be difficult to determine which conf items were used in a given run otherwise, and you don't want to clutter up the conf files with default values for variables that aren't even used in the run. 

The default value items would be added to the final conf that you could write out again, so the metplus_final.conf file would contain all of the default values used in the run, making it clear what was run.

**Comment by georgemccabe** [comment]
Wrapped getexe in met_util to check if the option is set in the config files. If it is not, warn and exit. If the exe item is set, check the path to make sure it is set correctly, or warn/exit if not. This cleans up the output and makes it clear which requested exe items are not set correctly.

Started doing the same for getdir. If OUTPUT_BASE is not set in the conf, metplus fails in the configuration step. If you forget to pass in a custom user config file, you get an error. With this change, the error message is now:

02/11 23:21:44.504 metplus (met_util.py:1682) ERROR: Directory OUTPUT_BASE does not exist at /path/to

while it previously was:

02/11 23:18:09.567 metplus (fileop.py:238) INFO: /path/to: make directory and parents
02/11 23:18:09.567 jlog (master_metplus.py:217) CRITICAL: master_metplus  failed: [Errno 13] Permission denied: '/path'
Traceback (most recent call last):
  File "/d1/mccabe/METplus/ush/master_metplus.py", line 213, in <module>
    main()
  File "/d1/mccabe/METplus/ush/master_metplus.py", line 70, in main
    p = config_metplus.setup(filename=cur_filename)
  File "/d1/mccabe/METplus.feature_177_pcp_combine_refactor/ush/config_metplus.py", line 145, in setup
    conf = config_launcher.launch(infiles, moreopt, cycle=cycle)
  File "/d1/mccabe/METplus.feature_177_pcp_combine_refactor/ush/config_launcher.py", line 275, in launch
    produtil.fileop.makedirs(conf.getdir('OUTPUT_BASE'), logger=logger)
  File "/d1/mccabe/METplus.feature_177_pcp_combine_refactor/ush/produtil/fileop.py", line 239, in makedirs
    os.makedirs(filename)
  File "/usr/local/python/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/python/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/path'
02/11 23:18:09Z run-METplus-CRITICAL:  master_metplus  failed: [Errno 13] Permission denied: '/path'

**Comment by georgemccabe** [comment]
Since sometimes we have METplus create the path when it doesn't exist, we can't check if a dir does not exist to decide to fail. Instead, we can check if it is set to '/path/to' and warn/exit if it is. This will ensure that any dirs that need to be set are set correctly from the default 'unset' /path/to value.

**Comment by georgemccabe** [comment]
For testing purposes, we want to allow the init function of a wrapper to succeed even if some of the items are not set. We do this so we can initialize a wrapper and then override conf values in the tests so that we don't need to pass in a config file to pytest.

To handle this, we can allow getdir, getstr, etc. to take a default value. The function will still fail if this is set to /path/to, but another default can be used to allow the wrapper to be initialized. The wrapper will have to have an additional check that the value is not set to the default value to allow successful execution.

For example, pcp_combine_wrapper calls:

self.c_dict[d_type+'_INPUT_DIR'] = self.p.getdir(d_type+'_PCP_COMBINE_INPUT_DIR', '')

The default value is an empty string. The wrapper can be initialized without this set, but the writer of the pytest must set it in the test before any functions that use it are run. This means that any functions that use this directory variable must check if it is set to an empty string, and fail gracefully if it is.

**Comment by georgemccabe** [comment]
Calls to getdir and getexe in the METplus wrappers repo now use the met_util version which performs error checking to report a useful error message / exit gracefully is a required variable is not set and set the default value in the config object.

Should we overwrite the final conf file at the end of execution with the updated config object? If we do that, we may want to remove some of the time items that are generated from the current run time of each run. Alternatively we could write a different file like metplus_final_w_defaults.conf.

We still need to create met_util versions of the other produtil getters (getstr, getint, getbool, etc.) so we can set the default values in the conf. We can rename met_util getraw_interp to getraw.

**Comment by NYColoraDan** [comment]
Is there an example of one or more time items that would be overwritten from the initial metplus_final.conf that is written as it currently works?

**Comment by georgemccabe** [comment]
Items would not be overwritten in the new version of the final conf. The final conf itself would be overwritten to contain all of the values that were set from a default value.

**Comment by NYColoraDan** [comment]
>  The final conf itself would be overwritten to contain all of the values that were set from a default value.

And that's all it would contain?

If so, we need to write a separate conf file then like you suggest (metplus_final_w_defaults.conf). I wouldn't want to wipe away conf items the user set so they can't see those.

**Comment by georgemccabe** [comment]
The overwritten final conf would contain all config variables, including the ones set by the user. I spoke with Dan and we think there is no harm in overwriting the final conf file to include the ones set by default values.

**Comment by georgemccabe** [comment]
This was implemented a while ago. I am unsure of the version where it was added (3.0?)
