### ISSUE TITLE
Setting regrid to_grid value in MET config from METplus

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#216]
Tina noticed that while she could set POINT_STAT_REGRID_TO_GRID in the METplus config to set the value of regrid { to_grid in the MET config file, she was unable to set it to NONE because it added quotes around the value.

**Comment by CPKalb** [comment]
When setting the to_grid entry (in the point_stat configuration file) to a named grid (ex: G218), quotes are required around the named grid ("G218").  However, to use NONE, these quotes should be absent, as using "NONE" causes MET to error out.  Since the quotes are hard copied into the met config file as such (to_grid    = "${REGRID_TO_GRID}";), a user cannot specify NONE in the METplus .conf file, without also removing these quotes from the met configuration file.

**Comment by georgemccabe** [comment]
Logic to set the regrid.to_grid value has been improved to properly exclude quotation marks from keywords like NONE and add them for actual grid definitions (unknown version, possible 3.0?)
