### ISSUE TITLE
Write test to make sure configuration variable documentation has been updated

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplus#227]
We need a proper test (that needs to pass before merging a feature branch and/or cutting a release) that compares the current list of conf variables in the documentation with the current list of conf variables available in the METplus wrappers. Since the conf variables are invoked many different ways in the wrappers, a proper test rather than a kludgy Python script that I wrote needs to be developed.

**Comment by georgemccabe** [comment]
We could write a script that searches for calls to config.get to see where config variables are being queried. However, some of these calls use variables in the name of the config variable, i.e. dtype = 'FCST', then calls self.config.getstr('config', dtype+'_IS_PROB'). This means we either need to have:

1) Human verification to determine what values can be set for the variable variable names and ensure that those are covered in the documentation

2) Come up with a standard name for variables used in this situation so that the script to parse the code knows what values are possible in that case. For example,

Rule: dtype can be 'FCST' or 'OBS'
dtype should not be used anywhere in the code where the value differs from FCST or OBS
Script to check config vars for documentation knows that dtype can only be 'FCST' or 'OBS' and checks all combinations for documentation

We could go farther to set dtype in a script called by METplus that sets it as a global variable so that it is defined in one place that is used by the code and the documentation script

**Comment by georgemccabe** [comment]
I set the priority to low not because this isn't an important issue, but because we are able to review the wrappers and add the appropriate information to the documentation by hand. Going forward, we should be smart about updating documentation when we add/change config variables, but it would be useful to have a test to ensure we did not miss anything.

**Comment by georgemccabe** [comment]
As discussed today, we decided that this issue is no longer relevant. The developers are responsible for documenting any new configuration variables that they add or change.
