### ISSUE TITLE
New Use Case: Satellite Altimetry data

### ISSUE THREAD

**Issue by AliciaBentley-NOAA** [dtcenter/METplus#2383]
## Describe the New Use Case ##
EMC needs to be able to read satellite altimetry data in order to verify significant wave height in GFS-wave and GEFS-wave forecasts. Satellite Altimetry data is in netCDF format. A python wrapper, similar to what was created for the [scatterometer Use Case](https://github.com/dtcenter/METplus/issues/1488), perhaps!

### Use Case Name and Category ###
Use case name is unknown for now, but should follow:
PointStat_fcstGFS_obsJASON3_satelliteAltimetry

### Input Data ###
JASON-3, SARAL/ALTIKA, and Sentinel-6a are satellite altimetry datasets. 
Data can be obtained from PO.DAAC (NASA). https://github.com/podaac/data-subscriber has code to read their altimeter data and more (pull out region, time, etc). Global would be good, since GFS-wave and GEFS-wave are global models.

Contact @AliciaBentley-NOAA for questions about input data and who should perform the Release Acceptance Testing step.

### Acceptance Testing ###
Success of this use case will be two things: a successful run through METplus with the datasets listed above, and meaningful output for EMC that they can utilize.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**
- [ ] Select **privacy**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept your changes. Merge branch into **develop**.
- [ ] Create a second pull request to merge **develop** into **develop-ref**, following the same steps for the first pull request.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by j-opatz** [comment]
This issue was approached with an attempt on the JASON-3 dataset first. The variable field of focus was chosen as swh_ocean, which is listed as significant wave height. The Python code to read in wind speeds from ASCAT METOP-B datasets was used as the base to read in the JASON-3 data. 

Ultimately the code was simplified, taking in a file name only with the code assuming the variable of interest is swh_ocean and limiting the time to whatever the input file has. This is partially the result of grouping in the JASON-3 dataset, which requires an xarray command that uses an exact group path name; an overly complicated routine of parent-child searches for a user-provided variable field could be used instead, but was not pursued.

The Python script appears to be successful, with a Plot-Point-Obs call utilizing the Python script producing the following image:

![Image](https://github.com/dtcenter/METplus/assets/59586397/2bccf8fe-baa1-4b87-bb4e-94a3e397b289)

Additional guidance is needed to know how the JASON-3 dataset may be utilized in verification: will multiple files with the same-ish time be read in at once? Was swh_ocean the correct variable field to evaluate? Is it necessary that the script be able to accept user-provided variables? What type of field should this be coded as (currently set to WDSATR, but could be changed) and does that need to be user-provided? What is the forecast dataset (GEFS or GFS are most likely candidates)?

**Comment by j-opatz** [comment]
Updating on this use case: It now is capable of reading in JASON-3, SARAL, and Sentinel-6a data files (controlled via string passed at runtime). The script is capable of processing variable fields as provided by the user, so it should be able to handle significant wave height, 10 meter wind speeds from the altimeter, and *most* other data fields in the file. JASON-3 and Sentinel-6a files are unique in that they use groups to store data, so if the selected variable is NOT in the hardcoded group, it may cause errors. However, he requested variable fields ARE in the hardcoded groups so it should be OK for its intended purpose.
GFS was the chosen candidate for a forecast verification and while global verification is the goal, the script was not required to read in multiple files at once, being called each time for a file ingest.
