### ISSUE TITLE
Provide support for user to generate plots separately from series analysis

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#25]
In the series analysis scripts series_by_init.py and series_by_lead.py, allow the user to determine whether to generate plots directly following a series analysis run, or re-run plot generation as a stand-alone action.

**Comment by georgemccabe** [comment]
series_by_init.py and series_by_lead.py have since been replaced by series_analysis_wrapper.py. There is an option to generate plots or not: SERIES_ANALYSIS_GENERATE_PLOTS/SERIES_ANALYSIS_GENERATE_ANIMATIONS. There is also a PlotDataPlane wrapper that can be added to the process list to generate plots of any data, so the desired logic from this issue is available.
