### ISSUE TITLE
Create new use case for SWPC CWDP project (grid_to_grid)

### ISSUE THREAD

**Issue by jvigh** [dtcenter/METplus#259]
This use case will compare two versions of the GloTEC model data: with and without COSMIC RO data. This use case is meant to replicate the results of Jonathan Vigh's vx5 verification run, which has been developed in a separate repo (https://github.com/NCAR/SWPC-CWDP-VX). This is my first attempt in creating a METplus use case - wish me luck!

**Comment by georgemccabe** [comment]
This work has been completed, but we still need to clean up a use case configuration to add to the repository because this use case utilizes new functionality that hasn't been covered in a use case prior to this work. We also need to obtain some sample data to add to a sample data tarball for the next release.
