### ISSUE TITLE
Update Cyclone Wrapper use case

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#266]
The Cyclone Wrapper use case is using data that is outside the date range in the /d1/METplus_Data directory and the tc_pairs portion of the config file needs to be fixed.

**Comment by jimfrimel** [comment]
Removing this comment.
It is incorrect.

**Comment by georgemccabe** [comment]
TRACK_DATA_DIR is a deprecated config variable and shouldn't be used. I
don't see it being used in cyclone_plotter_wrapper.py. I'm not
understanding how adding that variable back makes the use case work?
Jim - I was incorrect, as George indicated TRACK_DATA_DIR is not being used.

Also FYI, you can check if a package exists in python (differently for 2 vs
3). Here is more information:

https://stackoverflow.com/questions/14050281/how-to-check-if-a-python-module-exists-without-importing-it

Instead of commenting out cyclone plotter wrapper, we could check if
matplotlib and cartopy are found, and warn that they need to be installed
to run cyclone plotter if they aren't found.

**Comment by georgemccabe** [comment]
It looks like adding the following to cyclone_plotter.conf:

[filename_templates]
TC_PAIRS_ADECK_TEMPLATE =
{date?fmt=%Y%m}/a{basin?fmt=%s}q{date?fmt=%Y%m}*.gfso.{cyclone?fmt=%s}
TC_PAIRS_BDECK_TEMPLATE =
{date?fmt=%Y%m}/b{basin?fmt=%s}q{date?fmt=%Y%m}*.gfso.{cyclone?fmt=%s}
TC_PAIRS_OUTPUT_TEMPLATE =
{date?fmt=%Y%m}/{basin?fmt=%s}q{date?fmt=%Y%m%d%H}.gfso.{cyclone?fmt=%s}

and changing INIT_BEG to:

INIT_BEG = 20150301

makes the TcPairs portion of the plotter run correctly.

**Comment by bikegeek** [comment]
This use case is currently configured to use tropical cyclone data from 20150301 to 20150331.  This track (adeck and bdeck) data is now part of the data tarball that is included in each METplus release and on the host 'eyewall' under the /d1/METplus_Data/cyclone_track_feature/track_data directory.  This use case can be run by invoking both the TcPairs and CyclonePlotter wrappers.
