### ISSUE TITLE
Prepare METplus for distribution as a package via PyPI 

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#282]
Currently, METplus is unavailable as a 'package'/distribution to be used by other pieces of METplus (ie. METplotpy and other entities/users).  Ideally, we will need to get this distributed and hosted on PyPI, but licensing issues for the produtil portion will need to be addressed, as this was created by NOAA.

**Comment by georgemccabe** [comment]
Working to add setup.py script to allow users to install metplus package using pip locally. This is needed for the SWPC use case to make METplus available in Docker without having to add the directory to the python path.

We can revisit adding metplus to PyPi at a later date, as there may be more involved to do that due to potential licensing issues.

**Comment by georgemccabe** [comment]
Work has been done in branch feature_282_metplus_package. Initial testing seems promising, but it would be good to test it one of the driver scripts that are currently being used to call functions from the metplus.util and metplus.wrappers areas.
