### ISSUE TITLE
Replace Python 2.7 escape character with Python 3 escape character

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#296]
Running tests written in pytest (in a Python 3.6.3 environment) has resulted in DeprecationWarning in the met_util.py and produtil cluster.py scripts.  In this Stack Overflow solution (https://stackoverflow.com/questions/52335970/how-to-fix-string-deprecationwarning-invalid-escape-sequence-in-python), replace the escape character '/' with '//' or use raw strings.

**Comment by georgemccabe** [comment]
Minna,

I have already made these changes in my feature branch for python
embedding. You can assign this ticket to me and I will resolve it when I
merge my changes into develop.

**Comment by bikegeek** [comment]
Re-assigned to George, as requested.  Thanks George!

**Comment by jimfrimel** [comment]
This fix needs to be applied to produtil also.

**Comment by georgemccabe** [comment]
Here are the depracted warnings from produtil:

=
/d3/personal/mccabe/METplus/ush/produtil/config.py:677
  /d3/personal/mccabe/METplus/ush/produtil/config.py:677: DeprecationWarning: invalid escape sequence \.
    =(?P<value>.*)$''',arg)

/d3/personal/mccabe/METplus/ush/produtil/config.py:1337
  /d3/personal/mccabe/METplus/ush/produtil/config.py:1337: DeprecationWarning: invalid escape sequence \A
    if re.match('(?i)\A(?:T|\.true\.|true|yes|on|1)\Z',s):   return True

/d3/personal/mccabe/METplus/ush/produtil/config.py:1338
  /d3/personal/mccabe/METplus/ush/produtil/config.py:1338: DeprecationWarning: invalid escape sequence \A
    if re.match('(?i)\A(?:F|\.false\.|false|no|off|0)\Z',s): return False

/d3/personal/mccabe/METplus/ush/produtil/cluster.py:291
  /d3/personal/mccabe/METplus/ush/produtil/cluster.py:291: DeprecationWarning: invalid escape sequence \s
    if re.match('(?i)^processor\s*:\s*32',line):

/d3/personal/mccabe/METplus/ush/produtil/datastore.py:87
  /d3/personal/mccabe/METplus/ush/produtil/datastore.py:87: DeprecationWarning: invalid escape sequence \A
    _has_dcolon=re.compile('\A.*::.*\Z')

/d3/personal/mccabe/METplus/ush/produtil/datastore.py:91
  /d3/personal/mccabe/METplus/ush/produtil/datastore.py:91: DeprecationWarning: invalid escape sequence \A
    _has_dstar=re.compile('\A.*\*\*.*\Z')

/d3/personal/mccabe/METplus/ush/produtil/numerics.py:350
  /d3/personal/mccabe/METplus/ush/produtil/numerics.py:350: DeprecationWarning: invalid escape sequence \s
    m=re.match('\s*(?P<ipart>[+-]?\d+)\s*(?P<num>[+-]\d+)\s*/\s*(?P<den>\d+)',a)

/d3/personal/mccabe/METplus/ush/produtil/numerics.py:382
  /d3/personal/mccabe/METplus/ush/produtil/numerics.py:382: DeprecationWarning: invalid escape sequence \A
    if(re.match('\A(?:\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d|\d{10}|\d{12})\Z',d)):

/d3/personal/mccabe/METplus/ush/produtil/numerics.py:439
  /d3/personal/mccabe/METplus/ush/produtil/numerics.py:439: DeprecationWarning: invalid escape sequence \A
    \s*''', a)

**Comment by jimfrimel** [comment]
This issue is being closed and resolved vi this commit 326a2803dbf786b286c

This commit now makes the METplus produtil package fully python 3 compliant.

This ticket not only addressees the Deprecation warning BUT ALSO includes bringing in remaining python 3 changes.

If you recall, the METplus produtil is a subset of the full produtil package, and even within
the modules in common, there was code that was not used or being called by METplus (currently - though it could be in the future).  Some of that code needed to be updated to be python 3 compliant. 

Since these changes did modify produtil, a package used by all of METplus, prior to 
committing, the use cases and pytests were run comparing the before commit and after 
commit to make sure nothing broke.  This isn't to say all the use cases or pytests are working,  but rather the behavior before and after this commit is the same, AND therefore accepted to be committed.

The remaining python 3 changes were taken from  https://github.com/hafs-community/NCEPLIBS-pyprodutil  feature/HAFSpy3 branch commit 9aae9daef9

The produtil changes from this commit can be viewed by looking
at the metplus-python 3 branch of 
https://github.com/NOAA-EMC/NCEPLIBS-pyprodutil

Regarding the Deprecation Warning, after review, the engineering committee decided
to use raw strings, which is consistent with the rest of the METplus code base, rather than escaping and replacing '/' with '//'. So that change has also been implemented.

Additionally other minor topical changes and some cleanup was also integrated
that was missed (or rather incomplete) from the feature/HAFSpy3 branch changes.
