### ISSUE TITLE
TCMPRPlotter TITLE can not contain spaces. 

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#43]
Bug The Plot TCMPR TITLE = option that is defined in metplus.conf can not contain spaces.

**Comment by bikegeek** [comment]
Fixed by refactoring the run_all_times() and retrieve_optionals() to use a dictionary to separate the -opts from their values to avoid splitting up the text in the title.  Special handling of opts with lists (-dep, -lookin, and -plot) is required to ensure that produtil's exe is correctly invoking the commands to run the plot_tcmpr.R script.
