### ISSUE TITLE
Update Chapter 5 of the Tutorial

### ISSUE THREAD

**Issue by fentoad72** [dtcenter/METplus#444]
Update text, paths, and METplus wrappers from v2.2 to v3.0 to reflect changes in METplus

**Comment by j-opatz** [comment]
I have reviewed the chapter and have the following comments:

Splash page

—The tutorial has the user check for the METPLUS_PARM_BASE, but this was never set in the Ch 1 tutorial.
—For tc_stat and tc_pairs usage statements, an error message shows up first before the usage statements. Can this behavior be changed to match the other tool usage statements (i.e. no errors)?

TC-Stat Tool: general

—In the usage statement, the first parameter is listed as “lookin path”. The actual statement is “lookin source”.

Tc-Stat: Plotting with R

—Okular doesn’t seem to be available on default (Dakota) profiles. There should be instructions on how to set it up if it’s going to be used.

METplus use case: Track and intensity TCMPR

—The tutorial references METPLUS_PARM_BASE, but as mentioned previously, this was not set
  —In addition to this issue, none of the references to the .conf files work, so the use case cannot be completed

Series-Analysis Tool: configure

—The link for the MET user’s guide goes to v8.1
—In the blue output_stats section, the sal1l2 variable is missing; this should probably be added in

Series-Analysis Tool: output

—Link for MET user’s guide is for v8.1

METplus Use Case: Feature Relative 

—MET user’s guide (v8.1) and METplus user’s guide (broken link) need fixing
—As in the last use case (Track and intensity), METPLUS_PARM_BASE is referenced and the source of the feature_relative.conf file. This was not set up in chapter 1, so the use case can’t be completed.
—The name of Feature relative for the chapter (or section) title is a bit confusing unless the user reviews the content and sees the difference (by lead, by initialization time, etc.). Can these be differentiated in the menu name?

Tutorial Course Eval

—Should the title include “Jul 2019”?
—May not need to include “10 being the best”, since Google adds scale descriptors

METViewer: Time series of categorical Statistics plot

—The instructions mention that the necessary changes will be marked in blue, but nothing is marked in blue.
—The tutorial mentions “Series line type”, but METViewer has two columns that could be interpreted that way: “Line Type” and “Series Line Type”. This command is actually directing users to the “Line Type” option, may need to make that more clear

**Comment by bikegeek** [comment]
Made the following edits to the following sections:
=====================================

Chapter 5 TC-STAT: Plotting with R section
-------------------------------------------
- replaced instances of 'okular' with 'display'.  'display' was not available for the hosts during the previous tutorial

Chapter 5 Track Intensity TCMPR:
----------------------------------
- updated directory paths to use_cases/model_applications/tc_and_extra_tc

- updated TCMPR custom config file name to TCMPRPloterConfig_customize

- updated original tcmpr config file to Plotter_fcstGFS_obsGFS_RPlotting.conf

- consolidated Example 1 and Example 2 to Example, as these were consolidated into one example, using the Plotter_fcst_GFS_obsGFS_RPlotting.conf file

**Comment by fentoad72** [comment]
Modified Chapter 5 through (not including) Feature Relative and Tutorial Survey

**Comment by TaraJensen** [comment]
I'm done with this chapter

**Comment by fentoad72** [comment]
Closed unless errors are found testing on supporting NCAR, NOAA platforms (#468)
