### ISSUE TITLE
Refine use case testing by validating the output and Add regression testing.

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#494]
## Describe the Task ##

This is general and meant to document what I see as two important requirements that needs to be considered and added to the testing framework.

I would expect this to be either broken in to specific Sub-issues as those
are identified or just have there own tasks.

ONE:
IDEALLY Add logic to use case tests (stand alone wrappers and model application), where appropriate, to validate the output a test generates. 
This is not trivial. 

TWO:
Look in to adding Regression testing to the CI framework.
Consider pytest-regtest package.
Initially, setup and run regression tests outside of the CI framework, once that is 
working ... then automate it by adding it to Travis.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fentoad72** [comment]
taking over travisCI from jim frimel

**Comment by fentoad72** [comment]
Unsure on what's being done with this; are we actively working on it?

**Comment by georgemccabe** [comment]
This work has not been started. There are a few things that can be done to improve the tests. Here are some ideas:

* **Compare the output to some "truth" data to make sure nothing has changed** (unless the changes are expected)
Currently the use cases run and are considered successful if they run without errors. However, changes could cause the commands generated to change. The tests don't alert us to that.

* **Check all environment variables and commands that are generated to ensure they haven't changed**
The wrappers build commands that are run and set environment variables that are used by the MET tools. In theory, if all of the same values are set in the environment and the same commands are generated, then the results should not change. If they do, it is due to changes in the MET tools that are tests independently from the wrappers. The wrappers store a list of commands that are generated. We could also store the environment variables that are set by the wrappers for each of the commands and use that as "truth" data to ensure nothing has changed. Note that use cases that have 1 item in the PROCESS_LIST (met_tool_wrappers) are easier because all of the data needed to build the commands is available. Use cases with more than 1 process (most model_applications) are more difficult because the files needed for intermediate processes will not be able to find the data they need. There are potential ways to get around this. We could determine the list of files that should be generated by an app and create dummy files with the same names to trick the wrappers into thinking they are there. However, this will not work for tools that look at the actual contents of the files (SeriesBy cases?). Another option is to run the use cases to generate the output, then review the env vars and commands. However, it would be ideal if we didn't have to run the actual commands because some of the use cases take a very long time to run.

* **When an error occurs in a use case, print out the errors from that log file**
Currently if an error occurs in a MET tool, the Travis log mentions that the app returned a non-zero return code, but we can't see what that error is. We can parse out the log file that contains the error and output it (or just the relevant portion) to the Travis log so we can get a better look at what went wrong without having to rerun. 
An related improvement in the MET tools for python embedding to capture the errors from the python script (most commonly import errors) in the logs would be useful for this debugging, as that information is not available anywhere in Travis.

**Comment by georgemccabe** [comment]
The following have addressed this issue:
* Automated use case tests now compare against truth data for pull request events to ensure that the output has not changed
* Pytests have been added for many of the wrappers that check that different config settings produce the expected commands and set the appropriate environment variables.

These could be improved and added for the rest of the wrappers, but a basic framework to handling this is now in place. Closing this issue.
