### ISSUE TITLE
Add more logging to tc_gen_wrapper

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplus#576]
## Describe the Enhancement ##
When attempting to find -track or -genesis input files for tc_gen, it simply returns False if no files are found with no logging information reported for the user. It would be helpful to explicitly log which type of files (track or genesis) it was unable to find before returning.

### Time Estimate ###
1-2 hours

### Relevant Deadlines ###
NONE

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
@DanielAdriaansen you did not see an error because you did not specify a template. The template is required. The wrappers are supposed to check if required variables are set in the create_c_dict function, but it looks like I forgot to check for this in TCGenWrapper. I will make this fix. I will also add an error in find_data if there are no templates specified to make sure this is logged correctly even if the wrapper is not set up correctly.

If you did have a template specified and it didn't find any data, it would report a nice error telling you what you couldn't find:

DEBUG: Looking for TRACK_INPUT file /d1/projects/METplus/METplus_Data/met_test/tc_data/genesis/atcf/2016d
ERROR: (command_builder.py:543) Could not find TRACK_INPUT file /d1/projects/METplus/METplus_Data/met_test/tc_data/genesis/atcf/2016d using template {init?fmt=%Y}d

It looks like there is no error if no matches were found using wildcards, so I will add that as well. It does still output what it tried to find, so even though it isn't an error, it is in the logs:

DEBUG: Looking for GENESIS_INPUT file /d1/projects/METplus/METplus_Data/met_test/tc_data/genesis/suite1/2016d*/genesis*2016*
DEBUG: Wildcard file pattern: /d1/projects/METplus/METplus_Data/met_test/tc_data/genesis/suite1/2016d*/genesis*2016*
DEBUG: 0 files match pattern

Thanks for bring this to attention!

**Comment by DanielAdriaansen** [comment]
@georgemccabe I think you're right. I still wonder if it would be useful to report if no TRACK or no GENESIS files were found in tc_gen_wrapper.py, specifically line 310 and 322?

I guess your proposed fix to find_data would error out before we got to lines 310 and 322, but it just seems like if we make it to line 310 or 322, we have an empty list of required input data and so we should stop.

I was simply going to add:
`self.log_error(f'NO TRACK files found. TRACK files are required. Exiting.')`
`sys.exit(1)`

For example, instead of return False.

**Comment by georgemccabe** [comment]
@DanielAdriaansen that error message is unnecessary because find_data should be reporting it already. The fixes I made add some additional checking to ensure that an error is thrown if no data is found. We don't want to call sys.exit(1) anywhere in the wrappers. There is code that cleans things up before it exits and prints out the log file path that would be skipped if we exit. Also, we may be running for multiple run times, i.e. 2018, 2019, 2020, and we don't want to exit if 2018 is not available because then 2019 and 2020 wouldn't process even though they have good data.

**Comment by georgemccabe** [comment]
Really the wrapper should have had the error checking done in create_c_dict and then you wouldn't have gotten past the initialization step of the wrappers because you didn't have a required value (template). Either way, adding a check in find_data will prevent this from happening again even if the wrapper wasn't set up correctly. Also, it would silently skip a for loop in find_data if no files were found from wildcards and not report an error, so it is good that was added as well.

**Comment by DanielAdriaansen** [comment]
Thanks for the info on my suggestion I figured there was a more appropriate way than bailing inside the wrapper. I copied that code from tc_pairs_wrapper.py, although it looks like exit(1) and not sys.exit(1) is used but either way I at least tried to copy code from somewhere in the repo :).

**Comment by georgemccabe** [comment]
Ah, that wrapper needs to be refactored to match the new standard. Those values should be checked in create_c_dict. The self.log_error function automatically increments the error counter, so after initialization it would report that it was not set up correctly and exit before any wrappers in the process list are run. I can make an issue for that.

**Comment by georgemccabe** [comment]
This issue was resolved with linked PR. It uncovered a use case that was failing due to no matches in a wildcard expression. I fixed that case (missing input data). I created an issue for the TCPairs improvement discussed in this conversation (#578 ).
