### ISSUE TITLE
Align the user guide with get_relativedelta() in time_util.py

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplus#579]
The documentation here:
https://dtcenter.github.io/METplus/Users_Guide/systemconfiguration.html#time-interval-units

says 1 day = "1D", but get_relativedelta() in time_util.py expects "1d" (note lowercase vs. uppercase "D").

`        if unit_value == 'd':`
`            return relativedelta(days=time_value)`

Based on dateutil conventions for relativedelta, should it be "1d" or "1D"?

### Relevant Deadlines ###
NONE

### Funding Source ###
NONE

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **master_\<Version>**.
Branch name:  `bugfix_579_day_is_lower_case_d`
- [x] Fix the bug and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **master_\<Version>** and link the pull request to this issue.
Pull request: `bugfix <Issue Number> master_<Version> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Complete the steps above to fix the bug on the **develop** branch and link the pull request to this issue.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [x] Close this issue.

**Comment by georgemccabe** [comment]
Fixed typo in documentation in master_v3.1 (updated gh-pages) and develop.

Other users have accidentally used 1D instead of 1d and the error message may not always be clear. Consider adding a check and either error out if D is used in a template format, or change it to lower-case d and warn the user that they used the wrong notation.

**Comment by DanielAdriaansen** [comment]
@georgemccabe my vote per our discussion would be to error out if the user supplies "D", since it does not align with the standards we adopted from strftime.org. 

Speaking of which, do we link anywhere in the documentation to strftime.org? Or do we have a standards page in the documentation of various Python standards we adhere to? That might be a useful addition, at a minimum to have somewhere to point a user when error messages are raised in situations like this.

**Comment by georgemccabe** [comment]
There are links to the documentation on that webpage all over the user's guide:

https://dtcenter.github.io/METplus/search.html?q=strftime.org&check_keywords=yes&area=default

There are other error checks that could be done to the filename template tags. For example, I have see multiple cases where someone forgot a symbol in the tag, like {init?fmt%Y%m} (missing =). I think we should close this issue since we fixed the bad information in the user's guide and create a new issue to add better error checking to these tags. The checks would include looking for %D or %3D.

**Comment by georgemccabe** [comment]
Closing this issue and created a new issue to address adding better error checking in filename template tag parsing: #608
