### ISSUE TITLE
Implement a way to turn timing control off

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplus#600]
## Describe the New Feature ##
For certain MET tools, like tc_gen, the notion of looping over time (e.g. init_time_beg to init_time_end via init_increment) doesn't fit. It's simply a tool to collect all forecast files in a directory and all observation files in a directory, and compute metrics, regardless of the time range of those files. Is there a case to implement a new METplus config variable, for example USE_TIMING_INFO, which would be a boolean and True by default? In the event a user wanted to run a tool like tc_gen, they could set this to False, and METplus would then ignore timing controls like LOOP_BY and all associated configuration items.

The case for this support is that if a user is only calling tc_gen, then they have to set some arbitrary timing controls or METplus wrappers (tc_gen_wrapper.py) will not work.

### Time Estimate ###
Unknown

### Relevant Deadlines ###
NONE

### Funding Source ###
NONE

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
@DanielAdriaansen , I think we should consider treating tools that are designed to run once to process all data differently than some of the other wrappers or even consider the wrappers that handle TC data to be handled differently. 

The TC use cases often involve processing by storm instead of a given range of time even though a time range may be provided to subset. However, a series of times may need to be processed before running the TC tools. Lindsay's latest use case **(https://github.com/dtcenter/METplus/blob/master_v3.1/parm/use_cases/model_applications/medium_range/TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByLead_PyEmbed_IVT.conf)** is an example of this. It calls PyEmbedIngest wrapper for each run time to get the input data processed, then it calls some TC tools to read that data.

There are other tools, like StatAnalysis, that are run once for a range of times, but there are often another tool like GridStat that needs to loop over times and process each before running StatAnalysis on all of the output from GridStat. Disabling time looping for this use case wouldn't allow all of the data to process correctly.

We should review how all of the tools are used and try to come up with a better way to handle these situations without requiring LOOP_ORDER to be set in a certain way. For example, if we have PCPCombine, RegridDataPlane, GridStat, and StatAnalysis in the process list, we could run the 1st 3 tools while looping over time, then call StatAnalysis after everything prior has been processed.

**Comment by georgemccabe** [comment]
With the removal of LOOP_ORDER, users are now able to configure different time ranges/intervals for each wrapper by creating instance identifiers and setting the appropriate time looping variables for each instance (see [Instance Names in Process List](https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#instance-names-in-process-list). Many wrappers also support settings a runtime frequency (e.g. STAT_ANALYSIS_RUNTIME_FREQ) so users can specify how often a tool should be run. Setting this value to RUN_ONCE will run the tool one time without looping over the time values.

Further refactoring could be done to support runtime frequency settings in all wrappers. However, many wrappers don't necessarily need this support, as they are always run at the time intervals that they currently support (e.g. run once, run once per init/valid and forecast lead pair, etc.).

Closing this issue because the desired capabilities are now supported.
