### ISSUE TITLE
Report unknown conf items to the user at runtime, or warn when using defaults

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplus#601]
## Describe the New Feature ##
Write a new function (perhaps in met_util.py) to report any configuration items encountered that METplus doesn't know about, or perhaps check against a dictionary in parse_var_list? Exit if any encountered to force user to reconfigure?

OR

Always warn when using default values.

The particular issue that came up when a user was attempting to set the conf item:
FCST_PCP_COMBINE_OUTPUT_ACCUM

The user had inadvertently added an "i" in front of the "PCP", such that the conf item was:
FCST_iPCP_COMBINE_OUTPUT_ACCUM

In the pcp_combine_wrapper.py in setup_add_method(), it looks like the code has a default value if the user doesn't specify:
```python
        # if [FCST/OBS]_OUTPUT_[NAME/ACCUM] are set, use them instead of
        # [FCST/OBS]_VAR<n>_[NAME/LEVELS]
        if self.c_dict[f"{data_src}_OUTPUT_ACCUM"]:
            accum_string = self.c_dict[f"{data_src}_OUTPUT_ACCUM"]
        else:
            level = var_info[f'{data_src.lower()}_level']
            _, accum_string = util.split_level(level)
```

For this user, they wanted to combine 24 1-hr accumulation forecasts into a 24-hr accumulation to compare with 24-hr accumulation observations, but the default value for FCST_PCP_COMBINE_OUTPUT_ACCUM was set to 1-hr, since that was the level of the FCST_VAR1_LEVELS variable (I think). I don't take issue with the behavior, but a message informing the user of this behind-the-scenes setting of FCST_PCP_COMBINE_OUTPUT_ACCUM would be helpful in this case.

### Relevant Deadlines ###
NONE

### Funding Source ###
NONE

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
@DanielAdriaansen , we actually allow (and sometimes encourage) users to user their own METplus variables that they have defined, so we wouldn't want to fail if they have any set that aren't one of the reserved METplus variables.

We do want any use of default values to be output in the logs. We do this in all wrappers except for a few that need to be refactored (i.e. PCPCombine). The specific case you mentioned is not handled because we still support a legacy way to configure PCPCombine that reads the output accumulation from the FCST_ or OBS_VAR<n>_LEVELS value. I have brought this issue up in METplus meetings as recently as last week, but I am having trouble finding a GitHub issue that describes the work. I have a note to think of a good solution to handle backwards compatibility or give useful error messages to update configs. It is related to this closed issue: https://github.com/dtcenter/METplus/issues/509. If there is currently no issue for the related future work, we can create it and dump our thoughts into the comments to keep track of the discussion.

**Comment by DanielAdriaansen** [comment]
@georgemccabe great point about the custom items I had forgotten that. We could still warn for our "known" variables but still not exit, however your point about putting out default values in the logs will also solve this particular issue.

What do you mean by your last sentence- use this issue for our thoughts and comments? I am not aware of any other issue for related future work if you were asking me.

**Comment by georgemccabe** [comment]
@DanielAdriaansen , I couldn't find an issue for related future work. I likely wanted to come up with a well-thought solution before creating the ticket, but it seems useful to have a ticket where thoughts from others can be contributed.

**Comment by georgemccabe** [comment]
I created this issue: https://github.com/dtcenter/METplus/issues/602
The logic in PCPCombine to use values from var_info if accum is not set will likely be removed for these changes. If output accum is not explicitly specified, the wrapper will likely error out and force this to be set (unless it makes sense to pull the accum from var_info and warn the user to update their config?).

**Comment by DanielAdriaansen** [comment]
What is var_info...is that in the PCPCombine wrapper somewhere or referencing variable metadata from the input file?

Personally, I like the idea of erroring out and forcing the user to set the accum manually.

**Comment by georgemccabe** [comment]
parse_var_list pulls out the information from [FCST/OBS]_VAR<n>_[NAME/LEVELS/THRESH/OPTIONS] and puts them into a list of each name/level combination. The list is usually called var_list and var_info is the name given for each list item in the loop. METplus currently doesn't check any information inside the actual files (just filenames).

I agree of the preference to error out and force the user to set the accum. However, we may have users that have set up their use cases using the old convention. We want to ensure a smooth transition to the new approach so that their long running use cases don't just fail when they switch to 4.0 and it is unclear what to do to fix it.

**Comment by georgemccabe** [comment]
The logs include a message when a default value is used to help alert users if they have a typo in a variable name.
